=== RafaRoldan10/EjerciciosLMSGI/ArticulosFruteria.dtd
<!ELEMENT fruteria (articulos, ofertas?, recetasEspecialesDeLaTienda)>
<!ELEMENT articulos (articulo+)>
<!ELEMENT ofertas (#PCDATA | oferta)*>
<!ELEMENT articulo EMPTY>
<!ELEMENT oferta ANY>
<!ELEMENT recetasEspecialesDeLaTienda ((tartaDeZanahoria | tartaDeManzana), tomatesALaPueblerina, potajeDeGarbanzos)>
<!ELEMENT tartaDeZanahoria EMPTY>
<!ELEMENT tartaDeManzana EMPTY>
<!ELEMENT tomatesALaPueblerina EMPTY>
<!ELEMENT potajeDeGarbanzos EMPTY>
<!ATTLIST fruteria nombre CDATA #FIXED "Fruteria Los Manzanos">
<!ENTITY % atributo "nombre ID #REQUIRED tipo ( fruta | legumbre | hortaliza) 'fruta'">
<!ATTLIST articulo %atributo;>
<!ENTITY tienda "en Fruteria Los Manzanos">
<!ATTLIST oferta articulo IDREF #IMPLIED
                 articulosEspeciales IDREFS #IMPLIED>

=== RafaRoldan10/EjerciciosLMSGI/ArticulosFruteria.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE fruteria SYSTEM "ArticulosFruteria.dtd">

<fruteria nombre="Fruteria Los Manzanos">
    <articulos>
        <articulo nombre= "Zanahorias" tipo="hortaliza"/>
        <articulo nombre = "Naranjas" tipo="fruta"/>
        <articulo nombre= "Manzanas" tipo="fruta"/>
        <articulo nombre = "Tomates" tipo="hortaliza"/>
        <articulo nombre = "Garbanzos" tipo = "legumbre"/>
    </articulos>
    <ofertas>
       Las ofertas son:
        <oferta articulo= "Tomates">Consgiue esta oferta &tienda;</oferta>
        <oferta articulo = "Garbanzos"> Una de las mejores ofertas &tienda; </oferta>
        <oferta articulosEspeciales= "Manzanas Naranjas">Las mejores frutas &tienda; </oferta>
    </ofertas>
    <recetasEspecialesDeLaTienda>
        <tartaDeZanahoria/>
        <tomatesALaPueblerina/>
        <potajeDeGarbanzos/>
    </recetasEspecialesDeLaTienda>

</fruteria>
