=== RafaRoldan10/EjerciciosLMSGI/partesdecasa.dtd
<!ELEMENT casa (partes, personas)>
<!ELEMENT partes (cocina, jardin, (cochera | desvan), dormitorio*)>
<!ELEMENT personas (mama, papa, hermano+, mascota?)>
<!ELEMENT cocina ANY>
<!ELEMENT jardin ANY>
<!ELEMENT cochera ANY>
<!ELEMENT desvan ANY>
<!ELEMENT dormitorio (#PCDATA | cama | mesa)*>
<!ELEMENT cama EMPTY>
<!ELEMENT mesa EMPTY>
<!ELEMENT mama (#PCDATA)>
<!ELEMENT papa (#PCDATA)>
<!ELEMENT hermano (#PCDATA)>
<!ENTITY % atributo "nombre ID #REQUIRED aÃ±oNacimiento CDATA #IMPLIED familia CDATA #FIXED 'Perez'">
<!ATTLIST mama %atributo;>
<!ATTLIST papa %atributo;>
<!ATTLIST hermano %atributo;>
<!ATTLIST cocina colorPared (blanco | azul | gris) "blanco"
                 personaLocalizada IDREF #IMPLIED>
<!ATTLIST jardin personaLocalizada IDREF #IMPLIED>
<!ATTLIST dormitorio personaLocalizada IDREFS #IMPLIED>
<!ENTITY edad "su edad es">

=== RafaRoldan10/EjerciciosLMSGI/partesdecasa.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE casa SYSTEM "partesdecasa.dtd">

<casa>
    <partes>
        <cocina colorPared="blanco" personaLocalizada="Manuel">
        </cocina>
        <jardin personaLocalizada="María">
        </jardin>
        <cochera></cochera>
        <dormitorio personaLocalizada="Juan Mario"> Sus componentes son <cama></cama>
            <cama></cama>
            <mesa></mesa>
        </dormitorio>
    </partes>
      <personas>
        <mama nombre="María" añoNacimiento="1972" familia="Perez">
            &edad;51
        </mama>
        <papa nombre="Manuel" añoNacimiento="1971" familia="Perez">
            &edad;52
        </papa>
        <hermano nombre="Juan" añoNacimiento="2001" familia="Perez"> &edad;22 </hermano>
        <hermano nombre="Mario" añoNacimiento="2004" familia="Perez"> &edad; 19 </hermano>
     </personas>

</casa>
