=== RafaRoldan10/EjerciciosLMSGI/RealMadrid.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="realMadrid" type="tipoRealMadrid" />

<xs:complexType name="tipoRealMadrid" mixed="true">
    <xs:sequence>
        <xs:element name="anioFundacion" type="mixtoConValidacion"></xs:element>
        <xs:element name="futbol" type="tipoFutbol"></xs:element>
        <xs:element name="baloncesto" type="tipoBaloncesto"></xs:element>
    </xs:sequence>
</xs:complexType>

<xs:complexType name="tipoFutbol">
    <xs:all>
        <xs:element name="estadio" type="tipoEstadio"/>
        <xs:element name="jugadores" type="tipoJugadores"></xs:element>
        <xs:element name="jugadorLeyenda" type="tipoJugadorLeyemda"></xs:element>
    </xs:all>
    <xs:attribute name="anioComienzo" type="tipoAnioComienzo"></xs:attribute>
</xs:complexType>

<xs:complexType name="mixtoConValidacion">
    <xs:simpleContent>
      <xs:extension base="minimo4Caracteres">
        <xs:attribute name="presidente" type="xs:string" />
    </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  
  <xs:complexType name="tipoVinicius">
    <xs:attribute name="DNI" type="tipoDNI"></xs:attribute>
    <xs:attribute name="posicion" type="tipoPosicion"></xs:attribute>
    <xs:attribute name="anioLlegada" type="tipoAnioLlegada"></xs:attribute>
  </xs:complexType>
  
  
  <xs:simpleType name="tipoPosicion">
    <xs:restriction base="xs:string">
        <xs:enumeration value="portero"></xs:enumeration>
        <xs:enumeration value="centrocampista"></xs:enumeration>
        <xs:enumeration value="delantero"></xs:enumeration>
    </xs:restriction>
  </xs:simpleType>
  
  <xs:simpleType name="tipoDNI">
    <xs:restriction base="xs:string">
        <xs:pattern value="[0-9]{8}[A-Z]"/>
    </xs:restriction>
  </xs:simpleType>
 
  <xs:simpleType name="minimo4Caracteres">
    <xs:restriction base="xs:integer"/>
  </xs:simpleType>

  <xs:complexType name="tipoEstadio">
    <xs:attribute name="nombre" type="xs:string"></xs:attribute>
    <xs:attribute name="capacidad" type="xs:integer"></xs:attribute>
  </xs:complexType>

  <xs:complexType name="tipoJugadores" mixed="true">
    <xs:all>
        <xs:element name="vinicius" type="tipoVinicius"/>
        <xs:element name="bellingham" type="tipoVinicius"/>
        <xs:element name="courtois" type="tipoVinicius"/>
    </xs:all>
  </xs:complexType>
  
  <xs:simpleType name="tipoAnioComienzo">
    <xs:restriction base="xs:integer">
        <xs:minInclusive value="0"></xs:minInclusive>
        <xs:maxInclusive value="2023"></xs:maxInclusive>
    </xs:restriction>
  </xs:simpleType>

<xs:simpleType name="tipoAnioLlegada">
  <xs:restriction base="tipoAnioComienzo">
    <xs:minInclusive value="2000" />
    <xs:maxInclusive value="2023" />
  </xs:restriction>
</xs:simpleType>

<xs:simpleType name="dorsal">
  <xs:restriction base="xs:integer">
    <xs:minInclusive value="0" />
    <xs:maxInclusive value="99" />
  </xs:restriction>
</xs:simpleType>
<xs:complexType name="tipoBaloncesto">
    <xs:choice>
        <xs:element name="plantilla"></xs:element>
        <xs:element name="jugadoresBaloncesto" type="tipoJugadoresBaloncesto"></xs:element>
    </xs:choice>
    <xs:attribute name="anioComienzo" type="tipoAnioComienzo"></xs:attribute>
</xs:complexType>
<xs:complexType name="tipoJugadoresBaloncesto">
   <xs:all>
    <xs:element name="llull" type="tipoLlull"></xs:element>
    <xs:element name="tavares" type="tipoLlull"></xs:element>
   </xs:all>
</xs:complexType>
<xs:complexType name="tipoLlull">
    <xs:attribute name="posicion_dorsal" type="tipoLlullandTavares"></xs:attribute>
</xs:complexType>

<xs:simpleType name="tipoLlullandTavares">
    <xs:union memberTypes="dorsalBaloncesto posicionBaloncesto" />
  </xs:simpleType>  
  
  <xs:simpleType name="dorsalBaloncesto">
    <xs:restriction base="xs:integer">
      <xs:minInclusive value="0" />
      <xs:maxInclusive value="99" />
    </xs:restriction>  
  </xs:simpleType>
  
  
  <xs:simpleType name="posicionBaloncesto">
    <xs:restriction base="xs:string">
      <xs:enumeration value="ala"/>
      <xs:enumeration value="base"/>
      <xs:enumeration value="pivot"/>
      <xs:enumeration value="ala-pivot"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="tipoJugadorLeyemda">
    <xs:complexContent mixed="true">
      <xs:extension base="tipoVinicius">
      <xs:attribute name="anioSalida" type="xs:integer"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>  
</xs:schema>

=== RafaRoldan10/EjerciciosLMSGI/RealMadrid.xml
<?xml version="1.0" encoding="UTF-8"?>
<realMadrid xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="RealMadrid.xsd">
<anioFundacion presidente="Victor Montiel">1902</anioFundacion>
Sus secciones deportivas son:
  <futbol anioComienzo="1902">
   <estadio nombre="Santiago Bernabeú " capacidad="90000"/>
   <jugadores>
    Entre los más importantes están:
    <vinicius DNI="23243598F" posicion="delantero" anioLlegada="2018"></vinicius>
    <bellingham DNI="23802128L" posicion="centrocampista" anioLlegada="2023"></bellingham>
    <courtois DNI="73829210S" posicion="portero" anioLlegada="2018"></courtois>
   </jugadores>
   <jugadorLeyenda DNI="32846291A" posicion="delantero" anioLlegada="2009" anioSalida="2018">
       Su nombre es Crisitano Ronaldo
   </jugadorLeyenda>

  </futbol>
  <baloncesto anioComienzo="1970">
    <jugadoresBaloncesto>
        <llull posicion_dorsal="10"></llull>
        <tavares posicion_dorsal="pivot" ></tavares>
    </jugadoresBaloncesto>
  </baloncesto>
</realMadrid>
