=== RafaRoldan10/EjerciciosLMSGI/videoclub.dtd
<!ELEMENT videoclub (peliculas,ofertas)>
<!ELEMENT peliculas (tipos)>
<!ELEMENT tipos (terror, comedia, (aventura | anime))>
<!ELEMENT ofertas (#PCDATA | ofertaMensual | ofertaSemanal)*>
<!ELEMENT ofertaMensual (#PCDATA)>
<!ELEMENT ofertaSemanal (#PCDATA)>
<!ELEMENT terror (peliculaMasAlquiladaTerror,otraPelicula+, temaDelMes?)>
<!ELEMENT comedia (peliculaMasAlquiladaComedia,otraPelicula+, temaDelMes?)>
<!ELEMENT aventura (peliculaMasAlquiladaAventura,otraPelicula+, temaDelMes?)>
<!ELEMENT temaDelMes EMPTY>
<!ELEMENT peliculaMasAlquiladaTerror EMPTY>
<!ELEMENT peliculaMasAlquiladaComedia EMPTY>
<!ELEMENT peliculaMasAlquiladaAventura EMPTY>
<!ELEMENT otraPelicula (#PCDATA)>
<!ENTITY % atributo "nombre ID #REQUIRED lanzamiento CDATA #IMPLIED opinion CDATA #FIXED 'buena'">
<!ATTLIST peliculaMasAlquiladaTerror %atributo;>
<!ATTLIST peliculaMasAlquiladaComedia %atributo;>
<!ATTLIST peliculaMasAlquiladaAventura %atributo;>
<!ATTLIST ofertaMensual codigo IDREF #REQUIRED
                         disponible (si | no ) "si">
<!ATTLIST ofertaSemanal codigos IDREFS #REQUIRED
                         disponible (si | no ) "si">
<!ENTITY intro "La peli es:">

=== RafaRoldan10/EjerciciosLMSGI/videoclub.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE videoclub SYSTEM "videoclub.dtd">

<videoclub>
    <peliculas>
        <tipos>
            <terror>
                <peliculaMasAlquiladaTerror nombre="ExpedienteWarren" lanzamiento="2013" opinion="buena"/>
                <otraPelicula> &intro; Anabelle</otraPelicula>
                <temaDelMes/>
            </terror>
            <comedia>
                <peliculaMasAlquiladaComedia nombre="OchoApellidosVascos" lanzamiento="2014" opinion="buena"/>
                <otraPelicula> &intro; OchoApellidosCatalanes</otraPelicula>
            </comedia>
            <aventura>
                <peliculaMasAlquiladaAventura nombre="FastAndFurious8" lanzamiento="2017" opinion="buena"/>
                <otraPelicula> &intro; Indiana Jones</otraPelicula>
            </aventura>
        </tipos>
   </peliculas>
   <ofertas>
        Ofertas oto√±o:
        <ofertaMensual codigo="OchoApellidosVascos" disponible="si">1 peli gratis</ofertaMensual>
        <ofertaSemanal codigos="ExpedienteWarren  FastAndFurious8" disponible="si" >2 pelis por 1</ofertaSemanal>
        <ofertaSemanal codigos="FastAndFurious8 ExpedienteWarren" disponible="si">2 pelis por 1</ofertaSemanal>
   </ofertas>
</videoclub>
