=== RafaRoldan10/EjerciciosLMSGI/Desarrollar-solo-XSD/Mascotas y Youtube/youtube.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="youtube" type="tipoYoutube" />

  <xs:complexType name="tipoYoutube">
    <xs:sequence>
      <xs:element name="videos" type="tipoVideos"/>
      <xs:element name="publicidad" type="tipoPublicidad"/>
      <xs:element name="idiomasDisponibles" type="tipoIdiomasDisponibles"/>
    </xs:sequence>
  </xs:complexType>

  <xs:simpleType name="tipoIdiomasDisponibles">
    <xs:list itemType="tipoIdioma"/>
  </xs:simpleType>

  <xs:complexType name="tipoPublicidad">
    <xs:sequence>
        <xs:element name="anuncio" type="tipoAnuncio"/>
        <xs:element name="anuncioPatrocinado" type="tipoAnuncioPatrocinado"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="tipoAnuncio" mixed="false">
    <xs:sequence>
        <xs:element name="empresa"/>
        <xs:element name="bannersPorMinuto"></xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="tipoAnuncioPatrocinado">
    <xs:complexContent mixed="false">
      <xs:extension base="tipoAnuncio">
        <xs:sequence>
          <xs:element name="descuentoYouTube" type="xs:string" />
        </xs:sequence>
        <xs:attribute name="patrocinador" type="xs:string"/>
    </xs:extension>
    </xs:complexContent>
  </xs:complexType>  

  <xs:complexType name="tipoVideos">
    <xs:sequence>
        <xs:element name="video" type="tipoVideo"></xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="tipoVideo" mixed="true">
    <xs:all>
        <xs:element name= "url"/>
        <xs:element name="visualizaciones" type="tipoVisualizaciones"/>
        <xs:element name="comentarios" type="tipoComentarios"/>
        <xs:element name="subscriptores" type="tipoSubscriptores"/>
    </xs:all>
  </xs:complexType>
  
  <xs:simpleType name="tipoVisualizaciones">
    <xs:restriction base="xs:integer">
        <xs:minInclusive value="0"/>
        <xs:maxInclusive value="1000000"/>
    </xs:restriction>
  </xs:simpleType>
  
  <xs:complexType name="tipoComentarios">
    <xs:sequence>
        <xs:element name="buenos" type="tipoBuenos"/>
        <xs:element name="malos" type="xs:integer"/>
    </xs:sequence>
  </xs:complexType>

  <xs:simpleType name="tipoBuenos">
    <xs:restriction base="tipoVisualizaciones">
      <xs:minInclusive value="0" />
      <xs:maxInclusive value="200000" />
    </xs:restriction>  
  </xs:simpleType>
  
  <xs:complexType name="tipoSubscriptores">
    <xs:all>
        <xs:element name="subscriptor" type="tipoSubscriptor"/>
    </xs:all>
  </xs:complexType>

  <xs:complexType name="tipoSubscriptor">
    <xs:sequence>
        <xs:element name="fechaSubscripcion" type="tipoFechaSubscripcion"/>
        <xs:element name="comentarios" type="tipoComentariosVacio"/>
        <xs:element name="correoElectronico" type="tipoCorreoElectronico"/>
        <xs:element name="idioma" type="tipoIdioma"/>
    </xs:sequence>
    <xs:attribute name="codigo" type="tipoCodigo"></xs:attribute>
  </xs:complexType>

  <xs:simpleType name="tipoIdioma">
    <xs:union memberTypes="idiomasEspaniol idiomasIngles"></xs:union>
  </xs:simpleType>

  <xs:simpleType name="idiomasEspaniol">
    <xs:restriction base="xs:string">
        <xs:enumeration value="Francés"></xs:enumeration>
        <xs:enumeration value="Italiano"></xs:enumeration>
        <xs:enumeration value="Alemán"></xs:enumeration>
        <xs:enumeration value="Inglés"></xs:enumeration>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="idiomasIngles">
    <xs:restriction base="xs:string">
        <xs:enumeration value="Korean"></xs:enumeration>
        <xs:enumeration value="Chinese"></xs:enumeration>
        <xs:enumeration value="Japanese"></xs:enumeration>
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="tipoCorreoElectronico">
    <xs:sequence>
        <xs:element name="usuario" type="xs:string"/>
        <xs:element name="servidor" type="tipoServidor"/>
    </xs:sequence>
    <xs:attribute name="completo" type="xs:string"></xs:attribute>
  </xs:complexType>

  <xs:complexType name="tipoServidor">
    <xs:choice>
        <xs:element name="perro"/>
        <xs:element name="gato"/>
        <xs:element name="gmail"/>
    </xs:choice>
  </xs:complexType>

  <xs:complexType name="tipoComentariosVacio" mixed="false">
    <xs:attribute name="cantidad" type="xs:integer"></xs:attribute>
  </xs:complexType>
  
  <xs:simpleType name="tipoCodigo">
    <xs:restriction base="xs:string">
        <xs:pattern value="[0-9]{2}-\[[A-Z]{2}\]-[0-9]{2}"></xs:pattern>
    </xs:restriction>
  </xs:simpleType>
  
  <xs:complexType name="tipoFechaSubscripcion" mixed="false">
    <xs:attribute name="dia" type="xs:integer"></xs:attribute>
    <xs:attribute name="mes" type="xs:string"></xs:attribute>
    <xs:attribute name="anyo" type="tipoAnyo"></xs:attribute>
  </xs:complexType>

  <xs:simpleType name="tipoAnyo">
    <xs:restriction base="xs:string">
        <xs:enumeration value="2015"/>
        <xs:enumeration value="2016"/>
        <xs:enumeration value="2017"/>
        <xs:enumeration value="2018"/>
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== RafaRoldan10/EjerciciosLMSGI/Desarrollar-solo-XSD/Mascotas y Youtube/Examen_B_YouTube.xml
<?xml version="1.0" encoding="UTF-8"?>
<youtube xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="youtube.xsd">
	<videos>
		<video>El de la Cabra que parece que canta <!--contenido mixto--><!--xs:all-->
			<url>https://www.youtube.com/watch?v=3xQUF696nik</url>
			<visualizaciones>112000</visualizaciones><!--entre 0 y 1 millon-->
			<comentarios><!--usar xs:sequence-->
				<buenos>1200</buenos><!--entre 0 y 200000-->
				<malos>700</malos>
			</comentarios>
			<subscriptores>
				<subscriptor codigo="15-[AR]-56"><!--contenido validado con patrón-->
					<fechaSubscripcion dia="12" mes="febrero" anyo="2017"/> <!--vacio--><!--atributo anyo debe de ser una enumeracion del 2015 al 2018-->
					<comentarios cantidad="12"/><!--vacio-->
					<correoElectronico completo="rafa@gmail.com">
						<usuario>rafa</usuario>
						<servidor><gmail/></servidor><!--xs:choice de perro orca o delfin-->
					</correoElectronico>
					<idioma>Chinese</idioma><!--xs:union de los idiomas en inglés y en español-->
				</subscriptor>
			</subscriptores>
		</video>
	</videos>
	<publicidad>
		<anuncio>
			<empresa>Gilette</empresa>
			<bannersPorMinuto>40000</bannersPorMinuto>
		</anuncio>
		<anuncioPatrocinado patrocinador="Google"><!--anuncio patrocinado es una derivación de anuncio-->
			<empresa>Casa Tarradellas</empresa>
			<bannersPorMinuto>15000</bannersPorMinuto>
			<descuentoYouTube>23%</descuentoYouTube>
		</anuncioPatrocinado>
	</publicidad>
	<idiomasDisponibles>Francés Italiano Alemán Inglés Chinese Korean Japanese</idiomasDisponibles><!--xs:list-->
</youtube>
